apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: longhorn-system
resources:
  - https://raw.githubusercontent.com/longhorn/longhorn/v1.7.1/deploy/longhorn.yaml
patches:
  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value: 
          name: KUBELET_ROOT_DIR
          value: /var/snap/microk8s/common/var/lib/kubelet
    target:
      name: longhorn-driver-deployer
      kind: Deployment

---

